branch-defaults:
  master:
    environment: dev-env
global:
  application_name: SlamBook
  branch: null
  default_ec2_keyname: test
  default_platform: Node.js
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
